exports.fun = require('./fun');
exports.greeting = require('./greeting');
exports.imageSearch = require('./imageSearch');
exports.youtube = require('./youtube');
exports.stickers = require('./stickers');
exports.translate = require('./translate');
exports.speech = require('./speech');
exports.zodiac = require('./zodiac');
exports.simi = require('./simi')
exports.nfsw = require('./nfsw')
exports.sfw = require('./sfw')
exports.menus=require('./menus')
exports.misc=require('./misc')